package com.wendyapp.petapp.shared;


/*
 * class Pet includes information of each pet
 * petID is generated by Datastore
 * other info (petName, type, color, age, gender, owner) are from user input
 * 
 */

public class Pet implements java.io.Serializable{

	public String petID;
	private String petName;
	private String petType;
	private String petColor;
	private String petAge;
	private String petGender;
	private String petOwner;
	
	public Pet(){
		
	}

	public Pet(String name, String type, String color, String age, String gender, String owner) {
		this.petName = name;
		this.petType = type;
		this.petColor = color;
		this.petAge = age;
		this.petGender = gender;
		this.petOwner = owner;		
	}
	public Pet(String name, String type, String color, String age, String gender, String owner, String keyString) {
		this.petName = name;
		this.petType = type;
		this.petColor = color;
		this.petAge = age;
		this.petGender = gender;
		this.petOwner = owner;		
		this.petID = keyString;
	}

	
	public void setPetID(String id){
		this.petID = id;
	}
	
	public String getPetName(){
		return petName;
	}
	public String getPetType(){
		return petType;
	}
	public String getPetColor(){
		return petColor;
	}
	public String getPetAge(){
		return petAge;
	}
	public String getPetGender(){
		return petGender;
	}

	
	public String getOwnerName(){
		return petOwner;
	}
}
